# Generated by Django 3.0.7 on 2020-08-30 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hub', '0006_auto_20200830_2305'),
        ('milkdairy', '0015_auto_20200825_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('undelivered', 'undelivered'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered')], default='undelivered', max_length=50)),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.Deliveryboy')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milkdairy.daysrel')),
            ],
        ),
    ]
