# Generated by Django 3.0.7 on 2020-09-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20200903_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
