# Generated by Django 3.0.7 on 2020-09-08 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_auto_20200903_1850'),
        ('delivery', '0004_auto_20200903_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.Hub_detail'),
        ),
        migrations.DeleteModel(
            name='Orderrelaton',
        ),
    ]
