# Generated by Django 3.0.7 on 2020-08-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milkdairy', '0002_auto_20200810_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='milkdairy.Orders'),
        ),
    ]
