# Generated by Django 3.0.7 on 2020-08-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkdairy', '0004_auto_20200811_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='membership',
            field=models.CharField(default='Yes', max_length=10),
        ),
    ]
