# Generated by Django 3.0.7 on 2020-08-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkdairy', '0005_members_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=9999),
        ),
    ]
