# Generated by Django 3.0.7 on 2020-08-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkdairy', '0006_auto_20200812_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='January',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.IntegerField()),
                ('members_id', models.ManyToManyField(to='milkdairy.Members')),
            ],
        ),
    ]
