# Generated by Django 3.0.7 on 2020-08-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkdairy', '0008_auto_20200812_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='months',
            field=models.CharField(choices=[('january', 'january'), ('febuary', 'febuary'), ('march', 'march'), ('april', 'april')], default='unknown', max_length=20),
        ),
    ]
