# Generated by Django 3.0.7 on 2020-08-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkdairy', '0009_month_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='months',
            field=models.CharField(max_length=20),
        ),
    ]
