# Generated by Django 3.0.7 on 2020-08-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkdairy', '0010_auto_20200812_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='members_id',
            field=models.ManyToManyField(blank=True, to='milkdairy.Members'),
        ),
    ]
