# Generated by Django 3.0.7 on 2020-08-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkdairy', '0011_auto_20200812_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.CharField(max_length=3),
        ),
    ]
