# Generated by Django 3.0.7 on 2020-08-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkdairy', '0012_auto_20200812_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='month_id',
            field=models.ManyToManyField(blank=True, to='milkdairy.Month'),
        ),
    ]
