# Generated by Django 3.0.7 on 2020-08-13 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milkdairy', '0013_members_month_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='daysrel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_id', models.ManyToManyField(blank=True, to='milkdairy.Day')),
                ('month_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='milkdairy.Month')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='milkdairy.Members')),
            ],
        ),
    ]
