# Generated by Django 3.0.7 on 2020-08-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milkdairy', '0014_daysrel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='members_id',
        ),
        migrations.RemoveField(
            model_name='day',
            name='month_id',
        ),
        migrations.RemoveField(
            model_name='day',
            name='next_day',
        ),
        migrations.RemoveField(
            model_name='day',
            name='next_month_id',
        ),
        migrations.RemoveField(
            model_name='day',
            name='next_year',
        ),
        migrations.RemoveField(
            model_name='members',
            name='ending',
        ),
        migrations.RemoveField(
            model_name='members',
            name='month_id',
        ),
        migrations.RemoveField(
            model_name='members',
            name='starting',
        ),
    ]
