# Generated by Django 3.0.7 on 2020-09-02 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_hub_detail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('milkdairy', '0015_auto_20200825_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('number', models.IntegerField()),
                ('whatsaap_number', models.IntegerField()),
                ('address', models.CharField(max_length=400)),
                ('date', models.DateField(auto_now_add=True)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.Hub_detail')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
