# Generated by Django 3.0.7 on 2020-09-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milkdairy', '0016_user_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_data',
        ),
    ]
