# Generated by Django 3.0.7 on 2020-09-03 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20200903_1533'),
        ('milkdairy', '0020_auto_20200903_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummery',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.Deliveryboy'),
        ),
    ]
