# Generated by Django 3.0.7 on 2020-09-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('month', '0002_delete_january'),
        ('milkdairy', '0021_ordersummery_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='hub_id',
        ),
        migrations.DeleteModel(
            name='daysrel',
        ),
        migrations.DeleteModel(
            name='Hubs',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
