# Generated by Django 3.0.7 on 2020-09-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkdairy', '0022_auto_20200908_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='m_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
