# Generated by Django 3.0.7 on 2020-09-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkdairy', '0023_month_m_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='m_num',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
