# Generated by Django 3.0.7 on 2020-09-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkdairy', '0024_auto_20200909_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummery',
            name='status',
            field=models.CharField(default='in transit', max_length=20),
        ),
    ]
