# Generated by Django 3.0.7 on 2020-09-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('month', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='January',
        ),
    ]
