# Generated by Django 3.0.7 on 2020-08-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='email',
            field=models.EmailField(default='default@blank.com', max_length=225, unique=True),
        ),
        migrations.AddField(
            model_name='hub',
            name='full_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
