# Generated by Django 3.0.7 on 2020-08-28 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20200828_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hub',
            name='staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hub',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=225, null=True)),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.Hub')),
            ],
        ),
    ]
