# Generated by Django 3.0.7 on 2020-08-28 17:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_auto_20200828_2224'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hub',
            managers=[
                ('_group', django.db.models.manager.Manager()),
            ],
        ),
    ]
