# Generated by Django 3.0.7 on 2020-09-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20200902_1631'),
        ('hub', '0007_hub_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deliveryboy',
        ),
    ]
